services:
  nginx:
    build:
      context: .
      dockerfile: extras/nginx/Dockerfile
    image: nginx:1.22-snakeoil
    volumes:
      - ./extras/web/nginx-uwsgi.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "443:443"
    links:
     - webapp
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: philchristensen/django-slackbot:latest
    ports:
     - "8443:8443"
    environment:
      DJANGO_SETTINGS_MODULE: examples.settings
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: philchristensen/django-slackbot:latest
    command: manage.py run_slackbot
    environment:
      DJANGO_SETTINGS_MODULE: examples.settings
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: philchristensen/django-slackbot:latest
    command: manage.py run_scheduler
    environment:
      DJANGO_SETTINGS_MODULE: examples.settings
