---
name: semantic-release
run-name: Run the semantic-relase process
on:
  push:
    branches:
      - main
permissions:
  contents: read # for checkout
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 24.1.2
          extra_plugins: |
            @commitlint/config-conventional@19.5.0
            @semantic-release/changelog@6.0.3
            @semantic-release/exec@6.0.3
            @semantic-release/git@10.0.1
            conventional-changelog-conventionalcommits@8.0.0
            semantic-release@24.1.2
            semantic-release-replace-plugin@1.2.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_USERNAME: ${{ env.TWINE_USERNAME }}
          PYPI_TOKEN: ${{ secrets.TWINE_PASSWORD }}
